ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS phone VARCHAR(15);
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS profile_picture_url TEXT;
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS role VARCHAR(255);
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS industry VARCHAR(255);
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS preferred_work_types JSONB NOT NULL DEFAULT '[]';
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS languages JSONB NOT NULL DEFAULT '[]';
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS available_days JSONB NOT NULL DEFAULT '[]';
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS hours_start VARCHAR(8);
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS hours_end VARCHAR(8);
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS remote_pref VARCHAR(50);
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS currency VARCHAR(20);
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS education TEXT;
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS work_history TEXT;
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS resume_url TEXT;
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS linkedin_url TEXT;
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS certificates_url TEXT;
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS licenses_url TEXT;
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS government_id_url TEXT;
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS embedding_updated_at TIMESTAMPTZ;
ALTER TABLE technician_profiles ADD COLUMN IF NOT EXISTS embedding_version INTEGER NOT NULL DEFAULT 0;
